### ISSUE TITLE
iOS certificates

### ISSUE THREAD

**Issue by kschwerdtfeger** [flinthillsdesign/cvifs-issues#45]
Our iOS Distribution Certificate expires in 3 days. Is this a major problem? We've had no luck finding a way to renew it or create a new one.
![ios-certs](https://cloud.githubusercontent.com/assets/1081225/11639338/e3cb2768-9cf1-11e5-985a-26576b911f33.jpg)

**Comment by davegaeddert** [comment]
Hey @kschwerdtfeger, sorry I did get your email last week, it just got a little buried. I don't think there's anything we need to do here right now -- the certificates will expire and it won't affect the apps that are already in the App Store. We will need to renew the certificates when we do new work on the app and have to submit a new version to the App Store!

**Comment by kschwerdtfeger** [comment]
Very good. I'll pass it on. Thank you!
